version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: weather_db
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
